FROM ubuntu:21.04

ARG DEBIAN_FRONTEND=noninteractive
ARG NODE_MAJOR=20

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH $PYTHONPATH:/webodm
ENV PROJ_LIB=/usr/share/proj
ENV NODE_MAJOR=${NODE_MAJOR}

WORKDIR /webodm

RUN printf "deb http://old-releases.ubuntu.com/ubuntu/ hirsute main restricted\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute-updates main restricted\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute universe\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute-updates universe\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute multiverse\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute-updates multiverse\ndeb http://old-releases.ubuntu.com/ubuntu/ hirsute-backports main restricted universe multiverse" > /etc/apt/sources.list && \
    apt update && \
    apt -o Acquire::Retries=3 install -y --no-install-recommends curl gnupg ca-certificates && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    printf "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" > /etc/apt/sources.list.d/nodesource.list && \
    apt update && \
    apt -o Acquire::Retries=3 install -y --no-install-recommends \
    python3.9 python3-pip python3-setuptools python3-wheel python3.9-distutils git g++ python3.9-dev \
    libpq-dev binutils libproj-dev gdal-bin pdal libgdal-dev python3-gdal nginx certbot \
    gettext-base cron postgresql-client gettext tzdata nodejs ffmpeg
