version: '2.1'
services:
  webapp:
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh --create-default-pnode --setup-devenv\""
    ports:
      - "35729:35729"
      - "5678:5678"
    volumes:
      - .:/webodm
      - ./redis-tls-dev/certs:/certs:ro
    env_file:
      - ./.env
  worker:
    volumes:
      - .:/webodm
      - ./redis-tls-dev/certs:/certs:ro
    env_file:
      - ./.env
    ports:
      - "5679:5678"
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webodm_dev
  # broker:
  #   volumes:
  #     - ./redis-tls-dev/certs:/certs:ro
  #   command: >
  #     redis-server
  #     --tls-port 6379
  #     --port 0
  #     --tls-cert-file /certs/redis.crt
  #     --tls-key-file /certs/redis.key
  #     --tls-ca-cert-file /certs/ca.pem
  #     --tls-auth-clients no
  #     --requirepass "devpassword"
  #     --appendonly yes
  worker-2:
    image: notoriun/pgi_web:1.0.31
    container_name: worker-2
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - ${WO_MEDIA_DIR}:/webodm/app/media:z
      - .:/webodm
    depends_on:
      - db
      - broker
    restart: unless-stopped
    oom_score_adj: 250
    env_file:
      - ./.env
    ports:
      - "5680:5678"
  # worker-3:
  #   image: notoriun/pgi_web:0.0.14
  #   container_name: worker-3
  #   entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
  #   volumes:
  #     - ${WO_MEDIA_DIR}:/webodm/app/media:z
  #     - .:/webodm
  #   depends_on:
  #     - db
  #     - broker
  #   restart: unless-stopped
  #   oom_score_adj: 250
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "5681:5678"
  node-odm:
    deploy:
      replicas: 2

