version: '2.1'

services:
  webapp:
    env_file:
      - ./.env

  worker:
    env_file:
      - ./.env

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webodm_dev
