# Generated by Django 2.2.27 on 2024-10-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_task_orthophoto_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='organization_name',
            field=models.CharField(blank=True, default='PGI', help_text='The name of your organization', max_length=255, null=True, verbose_name='Organization name'),
        ),
    ]
