# Generated by Django 2.2.27 on 2024-09-24 23:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_task_orthophoto_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='s3_images',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='List s3 buckets with images', verbose_name='S3 buckets images'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='organization_name',
            field=models.CharField(blank=True, default='PGI', help_text='The name of your organization', max_length=255, null=True, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT'), (6, 'IMPORT_FROM_S3')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True, verbose_name='Pending Action'),
        ),
    ]
