# Generated by Django 2.2.27 on 2024-10-02 01:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20240925_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='downloading_s3_progress',
            field=models.FloatField(blank=True, default=0.0, help_text='Value between 0 and 1 indicating the downloading images from s3 progress (estimated) of this task', verbose_name='Downloading Images from S3 Progress'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_origin',
            field=models.IntegerField(choices=[(1, 'USER_UPLOAD'), (2, 'S3')], default=1, help_text='From where the image come.', verbose_name='Image Origin'),
        ),
        migrations.AddField(
            model_name='task',
            name='s3_images',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='List s3 buckets with images', verbose_name='S3 buckets images'),
        ),
        migrations.AddField(
            model_name='task',
            name='uploading_s3_progress',
            field=models.FloatField(blank=True, default=0.0, help_text='Value between 0 and 1 indicating the uploading images to s3 progress (estimated) of this task', verbose_name='Uploading Images to S3 Progress'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT'), (6, 'IMPORT_FROM_S3'), (7, 'IMPORT_FROM_S3_WITH_RESIZE'), (8, 'UPLOAD_TO_S3')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True, verbose_name='Pending Action'),
        ),
    ]
