# Generated by Django 2.2.27 on 2024-09-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20240925_0049'),
        ('app', '0040_auto_20240925_0052'),
    ]

    operations = [
    ]
