# Generated by Django 2.2.27 on 2024-10-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20241002_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload_in_progress',
            field=models.BooleanField(default=False, help_text='A flag indicating whether this task is in upload progress', verbose_name='Upload In Progress'),
        ),
    ]
