# Generated by Django 2.2.27 on 2024-09-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_20240926_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_origin',
            field=models.IntegerField(choices=[(1, 'USER_UPLOAD'), (2, 'S3')], default=1, help_text='From where the image come.', verbose_name='Image Origin'),
        ),
    ]
