# Generated by Django 2.2.27 on 2024-10-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_task_upload_in_progress'),
        ('app', '0040_auto_20241018_1203'),
    ]

    operations = [
    ]
