# Generated by Django 2.2.27 on 2025-02-10 11:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_merge_20241018_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_origin',
        ),
        migrations.AddField(
            model_name='task',
            name='s3_assets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='List s3 buckets with assets', verbose_name='S3 assets buckets'),
        ),
    ]
