# Generated by Django 2.2.27 on 2024-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_task_image_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT'), (6, 'IMPORT_FROM_S3'), (7, 'IMPORT_FROM_S3_WITH_RESIZE'), (8, 'UPLOAD_TO_S3')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True, verbose_name='Pending Action'),
        ),
    ]
