# Generated by Django 2.2.27 on 2024-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20241001_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='downloading_s3_progress',
            field=models.FloatField(blank=True, default=0.0, help_text='Value between 0 and 1 indicating the downloading images from s3 progress (estimated) of this task', verbose_name='Downloading Images from S3 Progress'),
        ),
        migrations.AddField(
            model_name='task',
            name='uploading_s3_progress',
            field=models.FloatField(blank=True, default=0.0, help_text='Value between 0 and 1 indicating the uploading images to s3 progress (estimated) of this task', verbose_name='Uploading Images to S3 Progress'),
        ),
    ]
