# Generated by Django 2.2.27 on 2025-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20250210_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='node_connection_retry',
            field=models.IntegerField(default=0, help_text='Current node connection retry', verbose_name='Current node connection retry'),
        ),
    ]
