# Generated by Django 2.2.27 on 2025-03-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_task_node_connection_retry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='s3_assets',
        ),
    ]
