# Generated by Django 2.2.27 on 2025-03-14 00:44

import shutil

from django.db import migrations

from app import models as app_models
from app.classes.task_files_uploader import TaskFilesUploader


def move_fotos_to_own_dir(apps, schema_editor):
    Task = apps.get_model("app", "Task")
    tasks_with_fotos360: list[app_models.Task] = Task.objects.filter(
        available_assets__contains=["foto360.jpg"]
    )

    for migration_task in tasks_with_fotos360:
        project = app_models.Project()
        project.id = migration_task.project_id
        task = app_models.Task(project=project, id=migration_task.id)
        current_foto_360_path = task.assets_path("foto360.jpg")
        TaskFilesUploader(task.pk).upload_foto360([current_foto_360_path], [])
        task.available_assets = [
            asset for asset in task.available_assets if asset != "foto360.jpg"
        ]
        task.save()
        try:
            shutil.rmtree(current_foto_360_path)
        except Exception as e:
            print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_remove_task_s3_assets"),
    ]

    operations = [migrations.RunPython(move_fotos_to_own_dir)]
