# Generated by Django 2.2.27 on 2025-03-19 01:30

from django.db import migrations

from app import models as app_models


def populate_available_assets(apps, schema_editor):
    Task = apps.get_model("app", "Task")

    for migration_task in Task.objects.all():
        project = app_models.Project()
        project.id = migration_task.project_id
        task = app_models.Task(id=migration_task.id, project=project)

        migration_task.available_assets = task.list_s3_available_assets()
        migration_task.save()


def empty_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_move_foto_360"),
    ]

    operations = [migrations.RunPython(populate_available_assets, empty_func)]
