# Generated by Django 2.2.27 on 2025-03-19 12:06

from django.db import migrations

from app import models as app_models


def asset_is_from_orthophoto(asset: str):
    simple_assets_dirs = [
        "fotos/",
        "videos/",
        "fotos_360/",
        "foto_giga/",
    ]

    for asset_dir in simple_assets_dirs:
        if asset.startswith(asset_dir):
            return False

    return True


def populate_available_assets(apps, schema_editor):
    Task = apps.get_model("app", "Task")

    for migration_task in Task.objects.all():
        project = app_models.Project()
        project.id = migration_task.project_id
        task = app_models.Task(id=migration_task.id, project=project)

        s3_assets = task.list_s3_available_assets()
        task.available_assets = [
            asset for asset in s3_assets if not asset_is_from_orthophoto(asset)
        ]
        task.update_available_assets_field(use_s3=True)
        migration_task.available_assets = task.available_assets
        migration_task.save()


def empty_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_available_assets_from_s3"),
    ]

    operations = [migrations.RunPython(populate_available_assets, empty_func)]
