# Generated by Django 2.2.27 on 2025-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_fix_orthophoto_available_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='node_error_retry',
            field=models.IntegerField(default=0, help_text='Current node error retry', verbose_name='Current node error retry'),
        ),
    ]
