# Generated by Django 2.2.27 on 2025-03-24 16:36

from django.db import migrations


def fix_tasks_restarting_with_partial(apps, schema_editor):
    Task = apps.get_model("app", "Task")

    Task.objects.filter(partial=True, pending_action__isnull=False).update(
        status=None, pending_action=None
    )


def empty_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_taskasset"),
    ]

    operations = [migrations.RunPython(fix_tasks_restarting_with_partial, empty_func)]
