# Generated by Django 2.2.27 on 2025-03-25 22:33

from django.db import migrations
from app.utils.file_utils import get_file_name


def fix_orthophoto_assets(apps, schema_editor):
    TaskAsset = apps.get_model("app", "TaskAsset")

    orthophoto_assets = TaskAsset.objects.filter(type=2)

    for asset in orthophoto_assets:
        if len(asset.task.s3_images) == 0:
            continue

        s3_filename = find_s3_asset_name(asset.name, asset.task.s3_images)

        if not s3_filename:
            continue

        asset.name = s3_filename
        asset.save()


def empty_func(apps, schema_editor):
    pass


def find_s3_asset_name(asset: str, s3_images: list[str]):
    for s3_image in s3_images:
        s3_filename = get_file_name(s3_image)

        if s3_filename in asset:
            return s3_filename

    return None


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_fix_restarting_partials"),
    ]

    operations = [migrations.RunPython(fix_orthophoto_assets, empty_func)]
