# Generated by Django 2.2.27 on 2025-03-29 01:25

from django.db import migrations, models


def fix_assets_origin_path(apps, schema_editor):
    TaskAsset = apps.get_model("app", "TaskAsset")

    for task_asset in TaskAsset.objects.all():
        task_asset.origin_path = task_asset.path
        task_asset.save(update_fields=("origin_path",))


def update_path_with_origin_path_on_task(apps, schema_editor):
    TaskAsset = apps.get_model("app", "TaskAsset")

    for task_asset in TaskAsset.objects.all():
        task_asset.path = task_asset.origin_path
        task_asset.save(update_fields=("path",))


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_auto_20250328_0216"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskasset",
            name="origin_path",
            field=models.TextField(
                default="",
                help_text="The origin path of asset. If starts with 's3://' that means it's from S3",
                verbose_name="Origin path",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            fix_assets_origin_path, update_path_with_origin_path_on_task
        ),
        migrations.RemoveField(
            model_name="taskasset",
            name="path",
        ),
    ]
