# Generated by Django 2.2.27 on 2025-04-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20250329_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssetFoto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
        migrations.CreateModel(
            name='TaskAssetFoto360',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
        migrations.CreateModel(
            name='TaskAssetFoto360Thumbnail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
        migrations.CreateModel(
            name='TaskAssetFotoGiga',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
        migrations.CreateModel(
            name='TaskAssetOrthophoto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
        migrations.CreateModel(
            name='TaskAssetVideo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.taskasset',),
        ),
    ]
