# Generated by Django 3.0.14 on 2025-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_taskassetfoto_taskassetfoto360_taskassetfoto360thumbnail_taskassetfotogiga_taskassetorthophoto_taska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskasset',
            name='status',
            field=models.IntegerField(choices=[(1, 'PROCESSING'), (3, 'ERROR'), (2, 'SUCCESS')], db_index=True, help_text='Current status of asset.', verbose_name='Status of asset'),
        ),
    ]
